# Workflow derived from https://github.com/pharmaverse/admiralci

name: CRAN Status Check
description: Creates a summary of issues reported on the CRAN status check page for a given R package

inputs:
  package:
    description: |
      Package name of the current R package deployed to CRAN
    required: true
    type: string
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.package }}
