name: manual-debug

on:
  workflow_dispatch:
    inputs:
      path:
        description: |
          Path to the R package root, if the package is not at the top level of
          the repository.
        default: "."
        required: false
        type: string
      package:
        description: |
          Package to check. If provided, it would have priority over the
          package on the repo.
        required: false
        default: ""
        type: string
      fail-on-error:
        description: |
          Logical, should the action error if CRAN checks are not ok?
        default: "false"
        required: false
        type: boolean
      create-issue:
        description: |
          Logical, create an issue on CRAN failed checks
        default: "true"
        required: false
        type: boolean
      issue-assignees:
        description: |
          Whom should the issue be assigned to if errors are
          encountered in the CRAN status checks?
          This is a comma-separated string of GitHub usernames.
          If undefined or empty, no assignments are made.
        default: ""
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check
        uses: dieghernan/cran-status-check@dev
        with:
          path: ${{ inputs.path }}
          package: ${{ inputs.package }}
          fail-on-error: ${{ inputs.fail-on-error }}
          create-issue: ${{ inputs.create-issue }}
          issue-assignees: ${{ inputs.issue-assignees }}

